<?php
/* Define page-specific extraction code */
$monster[][] = array();
$monster[1][0] = '//tr[contains(@class, "mgTable")]/td[2]/p/a[contains(@href, "mgUserInfo")]';
$monster[1][1] = '//tr[contains(@class, "mgTable")]/td[3]';
$monster[1][2] = '//tr[contains(@class, "mgTable")]/td[4]';
$monster[2][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[2][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[2][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[4][0] = '//div[contains(@class, "NonIndented")]/a';
$monster[4][1] = '//div[contains(@class, "NonIndented")]/p';
$monster[4][2] = '//div[contains(@class, "NonIndented")]/p';
$monster[3][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[3][1] = '//li/p[2]';
$monster[3][2] = '//li/p[1]';
$monster[5][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[5][1] = '//li/p[3]';
$monster[5][2] = '//li/p[1]';
$monster[6][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[6][1] = '//li/p[2]';
$monster[6][2] = '//li/p[1]';
$monster[7][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[7][1] = '//li/p[2]';
$monster[7][2] = '//li/p[1]';
$monster[8][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[8][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[8][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[9][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[9][1] = '//li/p[2]';
$monster[9][2] = '//li/p[1]';
$monster[10][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[10][1] = '//li/p[2]';
$monster[10][2] = '//li/p[1]';
$monster[11][0] = '//div[contains(@id, "personBlock")]/div[2]/a[not(contains(.,"Mr Test Test"))]';
$monster[11][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[11][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[12][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[12][1] = '//li/p[3]';
$monster[12][2] = '//li/p[1]';
$monster[13][0] = '//tr/td/p/a[contains(@href, "mgUserInfo")]';
$monster[13][1] = '//tr/td[3]';
$monster[13][2] = '//tr/td[4]';
$monster[14][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[14][1] = '//li/p[2]';
$monster[14][2] = '//li/p[1]';
$monster[15][0] = '//div[contains(@class, "mgThumbsList")]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[15][1] = '//li/p[2]';
$monster[15][2] = '//div[contains(@class, "mgThumbsList")]/ul/li/p[1]';
$monster[16][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[16][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[16][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[17][0] = '//table[contains(@summary, "Council Committee Members")]/tr/td/p/text()[1]';
$monster[17][1] = '//table[contains(@summary, "Council Committee Members")]/tr/td/p/text()[3]';
$monster[17][2] = '//table[contains(@summary, "Council Committee Members")]/tr/td/p/text()[2]';
$monster[18][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[18][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[18][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[19][0] = '//tr/td[2]';
$monster[19][1] = '//tr/td[4]';
$monster[19][2] = '//tr/td[3]';
$monster[20][0] = '//tr/td[2]/p/a[contains(@href, "mgUserInfo")]';
$monster[20][1] = '//tr/td[3]';
$monster[20][2] = '//tr/td[4]';
$monster[21][0] = '//tr[contains(@class, "d0") or contains(@class, "d1")]/td[1]/a';
$monster[21][1] = '//tr[contains(@class, "d0") or contains(@class, "d1")]/td[2]';
$monster[21][2] = '//tr[contains(@class, "d0") or contains(@class, "d1")]/td[3]';
$monster[22][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[22][1] = '//li/p[2]';
$monster[22][2] = '//li/p[1]';
$monster[23][0] = '//div[contains(@class, "row councillor")]/div[2]/h2/a';
$monster[23][1] = '//div[contains(@class, "row councillor")]/div[2]/p[2]/text()[2]';
$monster[23][2] = '//div[contains(@class, "row councillor")]/div[2]/p[1]';
$monster[24][0] = '//tr[contains(@class, "mgTable")]/td[1]/p/a[contains(@href, "mgUser")]';
$monster[24][1] = '//tr[contains(@class, "mgTable")]/td[3]';
$monster[24][2] = '//tr[contains(@class, "mgTable")]/td[4]';
$monster[25][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[25][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[25][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[27][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[27][1] = '//li/p[2]';
$monster[27][2] = '//li/p[1]';
$monster[28][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[28][1] = '//li/p[2]';
$monster[28][2] = '//li/p[1]';
$monster[29][0] = '//table/tr/td[2]/br[1]/preceding-sibling::text()';
$monster[29][1] = '//table/tr/td[3]/br[1]/preceding-sibling::text()';
$monster[29][2] = '//table/tr/td[3]/br[1]/following-sibling::text()';
$monster[30][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[30][1] = '//li/p[2]';
$monster[30][2] = '//li/p[1]';
$monster[31][0] = '//div[contains(@class, "content-details")]/ol/li[1]/span[2]';
$monster[31][1] = '//div[contains(@class, "content-details")]/ol/li[5]/span[2]';
$monster[31][2] = '//div[contains(@class, "content-details")]/ol/li[7]/span[2]';
$monster[32][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[32][1] = '//li/p[2]';
$monster[32][2] = '//li/p[1]';
$monster[33][0] = '//div[@class="mgThumbsList"]/ul/li/a';
$monster[33][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[33][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[34][0] = '//table[contains(@class, "council-tables")]/tr/td[1]/a';
$monster[34][1] = '//table[contains(@class, "council-tables")]/tr/td[3]';
$monster[34][2] = '//table[contains(@class, "council-tables")]/tr/td[2]';
$monster[36][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[36][1] = '//li/p[2]';
$monster[36][2] = '//li/p[1]';
$monster[38][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[38][1] = '//li/p[2]';
$monster[38][2] = '//li/p[1]';
$monster[39][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[39][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[39][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[40][0] = '//div[contains(@class, "mgThumbsList")]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[40][1] = '//li/p[2]';
$monster[40][2] = '//li/p[1]';
$monster[41][0] = '//div[contains(@class, "site-content")]/article/ul/li/a/h3';
$monster[41][1] = '//div[contains(@class, "site-content")]/article/ul/li/a/ul/li[2]';
$monster[41][2] = '//div[contains(@class, "site-content")]/article/ul/li/a/ul/li[1]';
$monster[42][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[42][1] = '//li/p[2]';
$monster[42][2] = '//li/p[1]';
$monster[44][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[44][1] = '//li/p[2]';
$monster[44][2] = '//li/p[1]';
$monster[45][0] = '//div[contains(@class, "item alt")]/h2/a[contains(@href, "councillors")]';
$monster[45][1] = '//div[contains(@class, "item alt")]/p[1]/a[1]';
$monster[45][2] = '//div[contains(@class, "item alt")]/p[1]/a[2]';
$monster[46][0] = '//tr/td[2]/a';
$monster[46][1] = '//tr/td[3]';
$monster[46][2] = '//tr/td[5]/a[1]';
$monster[47][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[47][1] = '//li/p[2]';
$monster[47][2] = '//li/p[1]';
$monster[48][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[48][1] = '//li/p[2]';
$monster[48][2] = '//li/p[1]';
$monster[49][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[49][1] = '//li/p[2]';
$monster[49][2] = '//li/p[1]';
$monster[50][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[50][1] = '//li/p[2]';
$monster[50][2] = '//li/p[1]';
$monster[51][0] = '//tr[contains(@class,"mgTable")]/td[2]/p/a[contains(@href, "mgUserInfo")]';
$monster[51][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[51][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[52][0] = '//tr/td[1]/a';
$monster[52][1] = '//tr/td[3]';
$monster[52][2] = '//tr/td[2]';
$monster[53][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[53][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[53][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[54][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[54][1] = '//li/p[2]';
$monster[54][2] = '//li/p[1]';
$monster[55][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[55][1] = '//li/p[2]';
$monster[55][2] = '//li/p[1]';
$monster[57][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[57][1] = '//li/p[2]';
$monster[57][2] = '//li/p[1]';
$monster[58][0] = '//div[contains(@class, "views-field-title")]/span/a';
$monster[58][1] = '//div[contains(@class, "views-field-field-party")]/div';
$monster[58][2] = '//div[contains(@class, "views-field-field-ward")]/div/a';
$monster[59][0] = '//ol[contains(@id, "councillorList")]/li/a';
$monster[59][1] = '//ol[contains(@id, "councillorList")]/li/@data-sort-party';
$monster[59][2] = '//ol[contains(@id, "councillorList")]/li/@data-sort-ward';
$monster[60][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[60][1] = '//li/p[2]';
$monster[60][2] = '//li/p[1]';
$monster[61][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[61][1] = '//li/p[2]';
$monster[61][2] = '//li/p[1]';
$monster[62][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[62][1] = '//li/p[2]';
$monster[62][2] = '//li/p[1]';
$monster[63][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[63][1] = '//li/p[2]';
$monster[63][2] = '//li/p[1]';
$monster[64][0] = '//ul[contains(@class, "list-person")]/li/h3/a';
$monster[64][1] = '//ul[contains(@class, "list-person")]/li/p[2]';
$monster[64][2] = '//ul[contains(@class, "list-person")]/li/p[1]';
$monster[65][0] = '//div[contains(@class, "view-content")]/h3/a';
$monster[65][1] = '//div[contains(@class, "views-field-field-party")]/div';
$monster[65][2] = '//div[contains(@class, "views-field-field-ward")]/div/a';
$monster[67][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[67][1] = '//li/p[2]';
$monster[67][2] = '//li/p[1]';
$monster[68][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[68][1] = '//li/p[2]';
$monster[68][2] = '//li/p[1]';
$monster[69][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[69][1] = '//li/p[2]';
$monster[69][2] = '//li/p[1]';
$monster[70][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[70][1] = '//li/p[2]';
$monster[70][2] = '//li/p[1]';
$monster[71][0] = '//tr/td[1]/a';
$monster[71][1] = '//tr/td[1]/a/following-sibling::text()[1]';
$monster[71][2] = '//tr/td[2]/a';
$monster[72][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[72][1] = '//li/p[2]';
$monster[72][2] = '//li/p[1]';
$monster[73][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[73][1] = '//li/p[2]';
$monster[73][2] = '//li/p[1]';
$monster[74][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[74][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[74][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[75][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[75][1] = '//li/p[2]';
$monster[75][2] = '//li/p[1]';
$monster[76][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[76][1] = '//li/p[2]';
$monster[76][2] = '//li/p[1]';
$monster[77][0] = '//table[contains(@class, "mgStatsTable tablesorter")][2]//tr/td[2]/p/a[contains(@href, "mgUserInfo")]';
$monster[77][1] = '//table[contains(@class, "mgStatsTable tablesorter")][2]//tr/td[3]';
$monster[77][2] = '//table[contains(@class, "mgStatsTable tablesorter")][2]//tr/td[4]';
$monster[78][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[78][1] = '//li/p[2]';
$monster[78][2] = '//li/p[1]';
$monster[79][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[79][1] = '//li/p[3]';
$monster[79][2] = '//li/p[1]';
$monster[80][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[80][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[80][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[82][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[82][1] = '//li/p[2]';
$monster[82][2] = '//li/p[1]';
$monster[83][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[83][1] = '//li/p[2]';
$monster[83][2] = '//li/p[1]';
$monster[84][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[84][1] = '//li/p[2]';
$monster[84][2] = '//li/p[1]';
$monster[85][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[85][1] = '//li/p[2]';
$monster[85][2] = '//li/p[1]';
$monster[86][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[86][1] = '//li/p[2]';
$monster[86][2] = '//li/p[1]';
$monster[87][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[87][1] = '//li/p[2]';
$monster[87][2] = '//li/p[1]';
$monster[88][0] = '//ul/li/h3/a/strong';
$monster[88][1] = '//ul/li/p[2]';
$monster[88][2] = '//ul/li/p[1]';
$monster[89][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[89][1] = '//li/p[3]';
$monster[89][2] = '//li/p[1]';
$monster[90][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[90][1] = '//li/p[2]';
$monster[90][2] = '//li/p[1]';
$monster[91][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[91][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[91][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[92][0] = '//h3[contains(@class, "councillorslist")]/a';
$monster[92][1] = '//dd[contains(@class, "councillorslist-party")]';
$monster[92][2] = '//dd[contains(@class, "councillorslist-ward")]';
$monster[93][0] = '//div[@class="mgThumbsList"]/ul/li/a[2]';
$monster[93][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[93][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[94][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[94][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[94][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[95][0] = '//table[@class="gvi"]/tr/td[1]/a';
$monster[95][1] = '//table[@class="gvi"]/tr/td[2]/a';
$monster[95][2] = '//table[@class="gvi"]/tr/td[4]/a';
$monster[96][0] = '//ul[contains(@class, "list__person")]/li/h3/a';
$monster[96][1] = '//ul[contains(@class, "list__person")]/li/p[2]';
$monster[96][2] = '//ul[contains(@class, "list__person")]/li/p[1]';
$monster[98][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[98][1] = '//li/p[2]';
$monster[98][2] = '//li/p[1]';
$monster[99][0] = '//table[@class="dataGrid"]/tr/td[3]/a[contains(@title, "Show details")]';
$monster[99][1] = '//table[@class="dataGrid"]/tr/td[1]/a/img/@alt';
$monster[99][2] = '//table[@class="dataGrid"]/tr/td[5]';
$monster[100][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[100][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[100][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[101][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[101][1] = '//li/p[2]';
$monster[101][2] = '//li/p[1]';
$monster[102][0] = '//table/tbody/tr/td[2]/p/a';
$monster[102][1] = '//table/tbody/tr/td[2]/p[2]';
$monster[102][2] = '//table/tbody/tr/td[2]/p[3]';
$monster[103][0] = '//li/a[contains(@href, "mgUserInfo")]';
$monster[103][1] = '//li/p[2]';
$monster[103][2] = '//li/p[1]';
$monster[104][0] = '//table/tbody/tr/td[1]/a';
$monster[104][1] = '//table/tbody/tr/td[2]/a';
$monster[104][2] = '//table/tbody/tr/td[3]';
$monster[105][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[105][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[105][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[107][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[107][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[107][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[109][0] = '//div[@class="site-main__content"]/article/ul/li/a/div[2]/h3';
$monster[109][1] = '//div[@class="site-main__content"]/article/ul/li/a/div[2]/ul/li[2]';
$monster[109][2] = '//div[@class="site-main__content"]/article/ul/li/a/div[2]/ul/li[1]';
$monster[110][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[110][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[110][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[111][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[111][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[111][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[112][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[112][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[112][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[114][0] = '//ul[@class="item-list item-list__rich councillors"]/li/h3/a';
$monster[114][1] = '//ul[@class="item-list item-list__rich councillors"]/li/p[2]';
$monster[114][2] = '//ul[@class="item-list item-list__rich councillors"]/li/p[1]';
$monster[116][0] = '//table/tbody/tr/td/a';
$monster[116][1] = '//table/tbody/tr/td/a/following-sibling::text()[not(contains(.,"MBE"))]';
$monster[116][2] = '//table/tbody/tr/td/strong';
$monster[117][0] = '//div[@id="contentArea"]/h2[@class="headerBackground"]';
$monster[117][1] = '//div[@id="contentArea"]/div/p[1]/text()[1]';
$monster[117][2] = '//div[@id="contentArea"]/div/p[1]/text()[2]';
$monster[118][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[118][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[118][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[119][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[119][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[119][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[122][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[122][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[122][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[123][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[123][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[123][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[124][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[124][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[124][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[125][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[125][1] = '//div[@class="mgThumbsList"]/ul/li/p[3]';
$monster[125][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[126][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[126][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[126][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[128][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[128][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[128][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[129][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[129][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[129][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[130][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[130][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[130][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[132][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[132][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[132][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[133][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[133][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[133][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[134][0] = '//table[@title="Council Member entries"]/tbody/tr/td[1]/a';
$monster[134][1] = '//table[@title="Council Member entries"]/tbody/tr/td[1]';
$monster[134][2] = '//table[@title="Council Member entries"]/tbody/tr/td[2]/a';
$monster[136][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[136][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[136][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[137][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[137][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[137][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[138][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[138][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[138][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[139][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[139][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[139][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[140][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[140][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[140][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[141][0] = '//a[contains(@href, "suffolk-coastal-district-councillors/councillor-")]';
$monster[141][1] = '//a[contains(@href, "suffolk-coastal-district-councillors/councillor-")]/following-sibling::text()';
$monster[141][2] = '//a[contains(@href, "suffolk-coastal-district-councillors/councillor-")]/following-sibling::text()';
$monster[142][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[142][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[142][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[143][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[143][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[143][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[144][0] = '//';
$monster[144][1] = '//';
$monster[144][2] = '//';
$monster[146][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[146][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[146][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[147][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[147][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[147][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[148][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[148][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[148][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[149][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[149][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[149][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[150][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[150][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[150][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[151][0] = '//div[@class="pairwrap"]/div/div[1]/div[1]/a';
$monster[151][1] = '//div[@class="pairwrap"]/div/div[1]/div[2]/p';
$monster[151][2] = '//div[@class="pairwrap"]/div/div[1]/strong';
$monster[152][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[152][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[152][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[153][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[153][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[153][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[154][0] = '//div[contains(@id, "personBlock")]/div[2]/a';
$monster[154][1] = '//div[contains(@id, "personBlock")]/div[3]/div[2]/img/@alt';
$monster[154][2] = '//div[contains(@id, "personBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[155][0] = '//a[contains(@href, "waveney-district-councillors/councillor-")]';
$monster[155][1] = '//a[contains(@href, "waveney-district-councillors/councillor-")]/following-sibling::text()';
$monster[155][2] = '//a[contains(@href, "waveney-district-councillors/councillor-")]/following-sibling::text()';
$monster[156][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[156][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[156][2] = '//div[@class="mgThumbsList"]/ul/li/p[1][not(contains(text(),"Committee"))]';
$monster[157][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[157][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[157][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[158][0] = '//article/ul[contains(@class, "list-person")]/li/h3/a';
$monster[158][1] = '//article/ul[contains(@class, "list-person")]/li/p[2]';
$monster[158][2] = '//article/ul[contains(@class, "list-person")]/li/p[1]';
$monster[160][0] = '//div[contains(@class, "alpha")]/div/div/div/div[contains(@class, "cls oBoxBodyInner")]/ul/li/span/span/span[@class="oBoxItemInner item-body-inner"]/span[@class="oBoxItemTitle item-title"]/a';
$monster[160][1] = '//span[@class="oBoxItemInner item-body-inner"]/span[2]';
$monster[160][2] = '//span[@class="oBoxItemInner item-body-inner"]/span[2]';
$monster[161][0] = '//div[@class="Counsillors"]/a[1]/img/@alt';
$monster[161][1] = '//div[@class="Counsillors"]/text()[5]';
$monster[161][2] = '//div[@class="Counsillors"]/text()[4]';
$monster[162][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[162][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[162][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[163][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[163][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[163][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[164][0] = '//ul[@class="councillors-list"]/li/h3/a';
$monster[164][1] = '//ul[@class="councillors-list"]/li/p[2]';
$monster[164][2] = '//ul[@class="councillors-list"]/li/p[1]';
$monster[165][0] = '//ul/li/a[contains(@href, "councillors-adur/cllr")]';
$monster[165][1] = '//ul/li/a[contains(@href, "councillors-adur/cllr")]';
$monster[165][2] = '//ul/li/a[contains(@href, "councillors-adur/cllr")]';
$monster[166][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[166][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[166][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[168][0] = '//li[@class="councillor"]/a/div/img/@alt';
$monster[168][1] = '//li[@class="councillor"]/a/div[2]/ul/li[2]';
$monster[168][2] = '//li[@class="councillor"]/a/div[2]/ul/li[1]';
$monster[169][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[169][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[169][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[170][0] = '//a[@title="further details for this councillor"]';
$monster[170][1] = '//tr/td[5]/text()';
$monster[170][2] = '//tr/td[2]/text()';
$monster[171][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[171][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[171][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[172][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[172][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[172][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[173][0] = '//p/a[contains(text(),"Councillor ")]';
$monster[173][1] = '//td[contains(text(),"Conservative") or contains(text(),"Labour") or contains(text(),"Liberal") or contains(text(),"Independent")]';
$monster[173][2] = '//td[contains(text(),"Conservative") or contains(text(),"Labour") or contains(text(),"Liberal") or contains(text(),"Independent")]/following-sibling::td';
$monster[174][0] = '//tbody/tr/td[2]/a';
$monster[174][1] = '//tbody/tr/td[3]';
$monster[174][2] = '//tbody/tr/td[4]';
$monster[175][0] = '//tbody/tr/td[2]/a';
$monster[175][1] = '//tbody/tr/td[3]';
$monster[175][2] = '//tbody/tr/td[4]';
$monster[176][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[176][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[176][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[177][0] = '//div[contains(@class, "councillor_more")]/div[contains(@class, "name")]';
$monster[177][1] = '//div[contains(@class, "councillor_more")]/div[contains(@class, "party")]';
$monster[177][2] = '//div[contains(@class, "councillor_more")]/div[contains(@class, "ward")]';
$monster[178][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[178][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[178][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[180][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[180][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[180][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[181][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[181][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[181][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[182][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[182][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[182][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[183][0] = '//li[@class="child"]/div/a';
$monster[183][1] = '//li[@class="child"]/div/a';
$monster[183][2] = '//div[@id="list"]/ul/li/div/p';
$monster[184][0] = '//table/tr/td/p/a';
$monster[184][1] = '//table/tr/td[2]';
$monster[184][2] = '//table/tr/td[4]';
$monster[185][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[185][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[185][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[186][0] = '//a[contains(@href,"mgUserInfo")]';
$monster[186][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[186][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[187][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[187][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[187][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[188][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[188][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[188][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[189][0] = '//tr[contains(@class, "mgTable")]/td[2]/p[1]/a';
$monster[189][1] = '//tr[contains(@class, "mgTable")]/td[3]';
$monster[189][2] = '//tr[contains(@class, "mgTable")]/td[4]';
$monster[190][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[190][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[190][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[191][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[191][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[191][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[193][0] = '//tr[contains(@class,"mgTable")]/td[2]/p/a[contains(@href,"mgUser")]';
$monster[193][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[193][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[194][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[194][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[194][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[195][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[195][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[195][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[196][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[196][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[196][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[197][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[197][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[197][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[199][0] = '//tbody/tr/td[1]/a';
$monster[199][1] = '//tbody/tr/td[1]';
$monster[199][2] = '//tbody/tr/td[2]/a';
$monster[200][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[200][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[200][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[201][0] = '//div[@class="desc"]/h3/a';
$monster[201][1] = '//div[@class="desc"]/p[2]';
$monster[201][2] = '//div[@class="desc"]/p[1]';
$monster[202][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[202][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[202][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[203][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[203][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[203][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[204][0] = '//tbody/tr/td[1]/a';
$monster[204][1] = '//tbody/tr/td[1]';
$monster[204][2] = '//tbody/tr/td[2]/a';
$monster[205][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[205][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[205][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[206][0] = '//dl[@class="person_box"]/dt/a/strong';
$monster[206][1] = '//dl[@class="person_box"]/dd[contains(text(), "Party")]';
$monster[206][2] = '//dl[@class="person_box"]/dd[contains(text(), "Ward")]';
$monster[207][0] = '//li[@class="clearfix"]/div/h3/a';
$monster[207][1] = '//li[@class="clearfix"]/div/p[2]';
$monster[207][2] = '//li[@class="clearfix"]/div/p[1]';
$monster[210][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[210][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[210][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[212][0] = '//div[@class="thumbnailCouncillors"]//a[text()]';
$monster[212][1] = '//div[@class="thumbnailCouncillors"]//text()[contains(., "Political Party")]';
$monster[212][2] = '//div[@class="thumbnailCouncillors"]//text()[contains(., "Ward")]';
$monster[213][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[213][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[213][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[214][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[214][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[214][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[216][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[216][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[216][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[217][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[217][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[217][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[218][0] = '//tbody/tr/td[2]/a';
$monster[218][1] = '//tbody/tr/td[4]';
$monster[218][2] = '//tbody/tr/td[3]';
$monster[219][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[219][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[219][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[220][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[220][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[220][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[221][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[221][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[221][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[223][0] = '//div[@class="cllrInfo"]/h2';
$monster[223][1] = '//div[@class="cllrInfo"]/h2/span';
$monster[223][2] = '//div[@class="cllrInfo"]/p';
$monster[224][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[224][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[224][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[225][0] = '//ul/li/a[contains(@href, "councillors-worthing/cllr")]';
$monster[225][1] = '//ul/li/a[contains(@href, "councillors-worthing/cllr")]';
$monster[225][2] = '//ul/li/a[contains(@href, "councillors-worthing/cllr")]';
$monster[227][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[227][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[227][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[228][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[228][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[228][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[229][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[229][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[229][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[230][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[230][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[230][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[231][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[231][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[231][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[232][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[232][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[232][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[234][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[234][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[234][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[235][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[235][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[235][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[236][0] = '//tbody/tr/td[1]/a';
$monster[236][1] = '//tbody/tr/td[3]';
$monster[236][2] = '//tbody/tr/td[2]';
$monster[237][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[237][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[237][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[238][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[238][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[238][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[239][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[239][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[239][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[240][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[240][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[240][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[241][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[241][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[241][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[242][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[242][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[242][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[243][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[243][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[243][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[244][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[244][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[244][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[245][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[245][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[245][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[246][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[246][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[246][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[247][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[247][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[247][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[248][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[248][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[248][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[249][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[249][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[249][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[250][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[250][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[250][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[251][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[251][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[251][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[252][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[252][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[252][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[253][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[253][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[253][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[254][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[254][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[254][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[255][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[255][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[255][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[256][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[256][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[256][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[257][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[257][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[257][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[258][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[258][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[258][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[259][0] = '//li[@class="list__item"]/article/a/h3/span';
$monster[259][1] = '//li[@class="list__item"]/article/a/ul/li[2]';
$monster[259][2] = '//li[@class="list__item"]/article/a/ul/li[1]';
$monster[260][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[260][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[260][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[261][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[261][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[261][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[262][0] = '//div[contains(@class, "mcc-cllr-group")]/h3/a';
$monster[262][1] = '//div[contains(@class, "mcc-cllr-group")]/p[2]/a';
$monster[262][2] = '//div[contains(@class, "mcc-cllr-group")]/p[1]/a';
$monster[263][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[263][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[263][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[264][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[264][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[264][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[265][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[265][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[265][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[266][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[266][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[266][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[267][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[267][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[267][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[269][0] = '//ul[contains(@class, "list-person")]/li/div/h3/a';
$monster[269][1] = '//ul[contains(@class, "list-person")]/li/div/p[2]';
$monster[269][2] = '//ul[contains(@class, "list-person")]/li/div/p[1]';
$monster[271][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[271][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[271][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[272][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[272][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[272][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[273][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[273][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[273][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[274][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[274][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[274][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[276][0] = '//ul[@class="person_box"]/li/h2/a';
$monster[276][1] = '//ul[@class="person_box"]/li/strong';
$monster[276][2] = '//ul[@class="person_box"]/li/p';
$monster[277][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[277][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[277][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[278][0] = '//ul[@class="boxed-list"]/li/h3/a';
$monster[278][1] = '//ul[@class="boxed-list"]/li/p[3]';
$monster[278][2] = '//ul[@class="boxed-list"]/li/p[2]';
$monster[279][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[279][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[279][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[280][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[280][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[280][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[281][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[281][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[281][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[282][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[282][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[282][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[283][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[283][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[283][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[284][0] = '//ul[@class="councillor-list"]/li/ul/li[2]/a/strong';
$monster[284][1] = '//ul[@class="councillor-list"]/li/ul/li[4]/img/@alt';
$monster[284][2] = '//ul[@class="councillor-list"]/li/ul/li[3]';
$monster[285][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[285][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[285][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[286][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[286][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[286][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[287][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[287][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[287][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[289][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[289][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[289][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[290][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[290][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[290][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[291][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[291][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[291][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[292][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[292][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[292][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[293][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[293][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[293][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[294][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[294][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[294][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[295][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][1]';
$monster[295][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[295][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[296][0] = '//table[@summary="Council Committee Members"]/tr/td/p/text()[1]';
$monster[296][1] = '//table[@summary="Council Committee Members"]/tr/td/p/text()[3]';
$monster[296][2] = '//table[@summary="Council Committee Members"]/tr/td/p/text()[2]';
$monster[297][0] = '//li/div/h3/a';
$monster[297][1] = '//li/div/p[2]';
$monster[297][2] = '//li/div/p[1]';
$monster[298][0] = '//tr/td[2]/strong[1]/a';
$monster[298][1] = '//tr/td[2]/strong[2]';
$monster[298][2] = '//tr/td[3]/strong';
$monster[299][0] = '//ul/li/a[contains(text(), "Councillor") and contains(@href, "council/wards/clack")]';
$monster[299][1] = '//ul/li/a[contains(text(), "Councillor")]/following-sibling::text()';
$monster[299][2] = '//ul/li/a[contains(@href, "council/wards/clack")]/@href';
$monster[300][0] = '//tr/td[1]/a';
$monster[300][1] = '//tr/td[1]';
$monster[300][2] = '//tr/td[2]/a';
$monster[301][0] = '//table/tbody/tr/td/strong[1]';
$monster[301][1] = '//table/tbody/tr/td/strong[1]';
$monster[301][2] = '//table/tbody/tr/td/a';
$monster[302][0] = '//tr/td/a';
$monster[302][1] = '//tr/td/text()[contains(.,"Councillor") or contains(.,"Leader of Council") or contains(.,"Provost")]';
$monster[302][2] = '//tr/td/img/@alt';
$monster[304][0] = '//dl[@class="person_box"]/dt/a/strong';
$monster[304][1] = '//dl[@class="person_box"]/dd[contains(text(), "Party")]';
$monster[304][2] = '//dl[@class="person_box"]/dd[contains(text(), "Ward")]';
$monster[305][0] = '//ul/li/a[contains(text(), "Councillor") and contains(@href, "ward") or contains(text(), "Provost") and contains(@href, "ward")]';
$monster[305][1] = '//ul/li/a[contains(text(), "Councillor") and contains(@href, "ward") or contains(text(), "Provost") and contains(@href, "ward")]';
$monster[305][2] = '//ul/li/a[contains(text(), "Councillor") and contains(@href, "ward") or contains(text(), "Provost") and contains(@href, "ward")]/@href';
$monster[306][0] = '//li/div/h3/a';
$monster[306][1] = '//li/div/p[2]';
$monster[306][2] = '//li/div/p[1]';
$monster[311][0] = '//ul[@class="item-list item-list__articles"]/li//a/text()[normalize-space()]';
$monster[311][1] = '//ul[@class="item-list item-list__articles"]/li/p[2]';
$monster[311][2] = '//ul[@class="item-list item-list__articles"]/li/p[1]';
$monster[313][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[313][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[313][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[315][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[315][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[315][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[316][0] = '//tr/td[1]/a';
$monster[316][1] = '//tr/td[1]';
$monster[316][2] = '//tr/td[2]/a';
$monster[318][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[318][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[318][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[319][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[319][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[319][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[320][0] = '//ul[contains(@class,"item-list item-list")]/li/h2/a';
$monster[320][1] = '//ul[contains(@class,"item-list item-list")]/li/ul/li[2]';
$monster[320][2] = '//ul[contains(@class,"item-list item-list")]/li/ul/li[1]';
$monster[321][0] = '//tr/td[2]/h5[1]';
$monster[321][1] = '//tr/td[2]/h5[1]';
$monster[321][2] = '//tr/td[2]/h5[2]';
$monster[322][0] = '//li/div/a';
$monster[322][1] = '//li/div/p/text()[2]';
$monster[322][2] = '//li/div/p/text()[1]';
$monster[323][0] = '//li/div[2]/p/a';
$monster[323][1] = '//li/div[2]/p[3]';
$monster[323][2] = '//li/div[2]/p[2]';
$monster[327][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[327][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[327][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[328][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[328][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[328][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[329][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[329][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[329][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[330][0] = '//div[contains(@class,"sys_subitem")]/div[1]/h3/a';
$monster[330][1] = '//dl/dd[2]';
$monster[330][2] = '//dl/dd[1]';
$monster[331][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[331][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[331][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[332][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[332][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[332][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[333][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[333][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[333][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[334][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[334][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[334][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[335][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[335][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[335][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[336][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[336][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[336][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[337][0] = '//tr[contains(@class,"color")]/td[2]/a';
$monster[337][1] = '//tr[contains(@class,"color")]/@class';
$monster[337][2] = '//tr[contains(@class,"color")]/td[2]/a';
$monster[338][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[338][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[338][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[340][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[340][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[340][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[341][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[341][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[341][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[342][0] = '//h2/a[contains(@href,"councillor/")]';
$monster[342][1] = '//span[@class="smallNotBold"]';
$monster[342][2] = '//span[@class="smallNotBold"]';
$monster[343][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[343][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[343][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[344][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[344][1] = '//div[contains(@class, "PersonBlock")]/div[4]/img/@alt';
$monster[344][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[345][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[345][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[345][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[346][0] = '//tr/td[2]/a';
$monster[346][1] = '//tr/td[3]';
$monster[346][2] = '//tr/td[4]';
$monster[347][0] = '//tr/td[1]/a';
$monster[347][1] = '//tr/td[2]';
$monster[347][2] = '//tr/td[3]/a';
$monster[350][0] = '//tr/td[2]/a';
$monster[350][1] = '//tr/td[3]/text()';
$monster[350][2] = '//tr/td[1]/a';
$monster[352][0] = '//table[contains(@summary,"councillors")]/tr[1]/th';
$monster[352][1] = '//table[contains(@summary,"councillors")]/tr/td/a[contains(@href,"search=parties")]';
$monster[352][2] = '//table[contains(@summary,"councillors")]/tr/td/a[contains(@href,"search=wards")]';
$monster[353][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[353][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[353][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[354][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[354][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[354][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[355][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[355][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[355][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[356][0] = '//tr/td[1]/a';
$monster[356][1] = '//tr/td[1]';
$monster[356][2] = '//tr/td[2]/a';
$monster[357][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[357][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[357][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[359][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[359][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[359][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[360][0] = '//ul[@class="item-list item-list--user"]/li/div/h3/a';
$monster[360][1] = '//ul[@class="item-list item-list--user"]/li/div/p[2]';
$monster[360][2] = '//ul[@class="item-list item-list--user"]/li/div/p[1]';
$monster[361][0] = '//tr[contains(@class,"mgTable")]/td[2]/p[1]/a';
$monster[361][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[361][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[362][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[362][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[362][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[363][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[363][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[363][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[364][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[364][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[364][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[365][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[365][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[365][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[366][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2][not(contains(.,"Marvin Rees"))]';
$monster[366][1] = '//div[@class="mgThumbsList"]/ul/li/p[2][not(contains(.,"Mayor"))]';
$monster[366][2] = '//div[@class="mgThumbsList"]/ul/li/p[1][not(.="")]';
$monster[367][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[367][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[367][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[368][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[368][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[368][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[369][0] = '//article/ul/li/h3/a';
$monster[369][1] = '//article/ul/li/p[2]';
$monster[369][2] = '//article/ul/li/p[1]';
$monster[370][0] = '//div[contains(@class, "PersonBlock")]/div[2]/a';
$monster[370][1] = '//div[contains(@class, "PersonBlock")]/div[3]/div[2]/img/@alt';
$monster[370][2] = '//div[contains(@class, "PersonBlock")]/div[3]/span/following-sibling::text()[1]';
$monster[371][0] = '//div[@class="mix-container"]/div/div[@class="councillor-name"]';
$monster[371][1] = '//div[@class="mix-container"]/div/div[@class="councillor-party"]';
$monster[371][2] = '//div[@class="mix-container"]/div/div[@class="councillor-ward"]';
$monster[372][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[372][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[372][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[373][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[373][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[373][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[374][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[374][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[374][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[376][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[376][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[376][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[377][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[377][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[377][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[378][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[378][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[378][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[379][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[379][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[379][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[380][0] = '//tbody/tr/td[1]/a';
$monster[380][1] = '//tbody/tr/td[3]';
$monster[380][2] = '//table[@class="views-table cols-3 table"]/tbody/tr/td[2]';
$monster[381][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[381][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[381][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[382][0] = '//ul/li[@class="col-sm-4"]/a';
$monster[382][1] = '//ul/li[@class="col-sm-4"]/p';
$monster[382][2] = '//ul/li[@class="col-sm-4"]/p';
$monster[383][0] = '//tr[contains(@class,"mgTable")]/td[2]/p[1]/a';
$monster[383][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[383][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[384][0] = '//tr[contains(@class,"mgTable")]/td[2]/p[1]/a';
$monster[384][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[384][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[385][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[385][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[385][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[386][0] = '//div[@class="councillors"]/ul/li/a[2]';
$monster[386][1] = '//div[@class="councillors"]/ul/li/p[2]';
$monster[386][2] = '//div[@class="councillors"]/ul/li/p[1]';
$monster[388][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[388][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[388][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[389][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[389][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[389][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[390][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[390][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[390][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[391][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[391][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[391][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[392][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[392][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[392][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[393][0] = '//td/p/a[contains(@href,"mgUserInfo")]';
$monster[393][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[393][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[394][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[394][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[394][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[395][0] = '//tr[contains(@class,"mgTable")]/td[2]/p[1]/a';
$monster[395][1] = '//tr[contains(@class,"mgTable")]/td[3]';
$monster[395][2] = '//tr[contains(@class,"mgTable")]/td[4]';
$monster[396][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[396][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[396][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[397][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[397][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[397][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[398][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[398][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[398][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[399][0] = '//h3[contains(@class, "sys_subitem")]/a';
$monster[399][1] = '//dl/dd[contains(@class, "sys_councillorslist-party")]';
$monster[399][2] = '//dl/dd[contains(@class, "sys_councillorslist-ward")]';
$monster[400][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[400][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[400][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[401][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")][2]';
$monster[401][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[401][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[402][0] = '//p/a[contains(@class,"sys_0 sys_t12") and contains(@href,"councillors")]';
$monster[402][1] = '//p/a[contains(@class,"sys_0 sys_t12") and contains(@href,"councillors")]/following-sibling::text()[contains(.,"Con")][1]|//p[contains(text(),"Party:")]/text()[1]';
$monster[402][2] = '//p[contains(text(),"Ward: ")]';
$monster[403][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[403][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[403][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[404][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[404][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[404][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[405][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[405][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[405][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[406][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[406][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[406][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[1003][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[1003][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[1003][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[1004][0] = '//div[@class="col-sm-8"]/h3';
$monster[1004][1] = '//div[@class="col-sm-8"]/p[1]';
$monster[1004][2] = '//div[@class="col-sm-8"]/p[2]';
$monster[1005][0] = '//div[@class="mgThumbsList"]/ul/li/a[contains(@href, "mgUserInfo")]';
$monster[1005][1] = '//div[@class="mgThumbsList"]/ul/li/p[2]';
$monster[1005][2] = '//div[@class="mgThumbsList"]/ul/li/p[1]';
$monster[1007][0] = '//div[@class="member-search"]/h3';
$monster[1007][1] = '//div[@class="member-search"]/p[1]';
$monster[1007][2] = '//div[@class="member-search"]/p[2]';
$monster[1008][0] = '//h3[@class="heading-min"]/a';
$monster[1008][1] = '//h3[@class="heading-min"]/following-sibling::p';
$monster[1008][2] = '//h3[@class="heading-min"]/following-sibling::p';
$monster[1011][0] = '//h3';
$monster[1011][1] = '//h3/following-sibling::p/text()[1]';
$monster[1011][2] = '//h3/following-sibling::p/text()[contains(.,"Area:")]';

/* Search strings for this file */
$name = $xpath->query($monster[$councilNumber][0]);
$party = $xpath->query($monster[$councilNumber][1]);
$ward = $xpath->query($monster[$councilNumber][2]);

/* Convert scraped data to arrays n, p and w */
foreach($name as $item) {$n[] = utf8_decode(str_replace("&nbsp;", "", htmlentities(addslashes(trim($item->nodeValue)), null, 'utf-8')));}
foreach($party as $item) {$p[] = str_replace("&nbsp;", "", htmlentities(addslashes(trim($item->nodeValue)), null, 'utf-8'));}
foreach($ward as $item) {$w[] = str_replace("&nbsp;", "", addslashes(trim($item->nodeValue)));}

?>
